apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: devsecops-internship
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: node-port
          containerPort: 9000
        - name: master-port
          containerPort: 9092
        volumeMounts:
          - name: sonar-data
            mountPath: /opt/sonarqube/data
          - name: sonar-data
            mountPath: /opt/sonarqube/logs
          - name: sonar-data
            mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonar-data
          hostPath:
            path: /sonar_data

---

kind: Service
apiVersion: v1
metadata:
  name: sonarqube-svc
  namespace: devsecops-internship
spec:
  selector:
    app: sonarqube
  type: LoadBalancer
  ports:
  - name: node-port
    port: 9000
    targetPort: 9000
  - name: master-port
    port: 9092
    targetPort: 9092
