apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: devsecops-internship
data:
  vault-local-config: |
    {
      "backend": { "file": { "path": "/vault/file" } },
      "default_lease_ttl": "168h",
      "max_lease_ttl": "720h",
      "ui": true
    }
